system:
  defaultStoragePath: /Users/xielibo/uploadPath/gausstool
  whitelist:
    enabled: false
server:
  port: 9494
  servlet:
    context-path: /
logging:
  file:
    path: /visualtool-api/logs/
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.opengauss.Driver
    url: jdbc:opengauss://120.48.145.206:5432/lhf?currentSchema=public
    username: jim0847
    password: umqb63LkGTPDDfXv
    druid:
      test-while-idle: false
      test-on-borrow: true
      validation-query: "select 1"
      validation-query-timeout: 10000
      connection-error-retry-attempts: 0
      break-after-acquire-failure: true
      max-wait: 3000
swagger:
  enabled: true
  pathMapping: /dev-api
plugin:
  sortInitPluginIds:
  decrypt:
    enable: false
    className: com.gitee.starblues.common.cipher.AesPluginCipher
    plugins:
      - pluginId: example-basic-1
        props:
          secretKey: mmfvXes1XckCi8F/y9i0uQ==
  version: 0.0.0

